robots.txt
Fix #11 
Test URLs:
- After: https://issue11--clarkcountynv--aemsites.aem.live/
=> Provisioning robots.txt

blocks/header/header.css, scripts/delayed.js, scripts/scripts.js, scripts/utils.js, styles/styles.css
Fix #10 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/
- After: https://issue10-headerv2--clarkcountynv--aemsites.aem.page/
=> Header further improvisation

blocks/header/header.css, blocks/header/header.js, scripts/delayed.js, styles/styles.css
Fix #15 
Test URLs:
- After: https://issue15-headerv4--clarkcountynv--aemsites.aem.live/
=> Issue15 header Animations 

blocks/tabs/tabs.css, blocks/tabs/tabs.js, styles/styles.css
Fix #20 
Test URLs:
- After: https://issue20-tabs--clarkcountynv--aemsites.aem.live/
=> Issue20 tabs block for both desktop & mobile view

blocks/header/header.css
Fix #24 
Test URLs:
- After: https://issue1-nav--clarkcountynv--aemsites.aem.live/
=> Taking care of the header bugs which are impacting Footer

styles/styles.css
Fix #27 
Test URLs:
- After: https://issue27-bug--clarkcountynv--aemsites.aem.live/
=> Taking care of bug

blocks/header/header.css, blocks/header/header.js, scripts/delayed.js, scripts/utils.js, styles/styles.css
Fix #8 
Test URLs:
- After: https://issue8-translations--clarkcountynv--aemsites.aem.live/
=> Google Translations Implementation

blocks/carousel/carousel.css, blocks/carousel/carousel.js
Bringing new carousel in line with current carousel prior to adding mobile compatability
Fix #36 
Test URLs:
- After: https://carousel-cont--clarkcountynv--aemsites.aem.live/
=> Carousel cont - updates to bring desktop view in line with current site

blocks/header/header.css, blocks/header/header.js
Fix #31 
Test URLs:
- After: https://issue31-breadcrumbs--clarkcountynv--aemsites.aem.live/
Put in some place holders to test please try https://issue31-breadcrumbs--clarkcountynv--aemsites.aem.page/government/assessor/make_a_payment/pay_single_manufactured_home_account/owner-name
=> breadcrumbs feature

blocks/accordion-ml/accordion-ml.js, blocks/header/header.css, blocks/tabs/tabs.css, blocks/tabs/tabs.js, styles/styles.css
Fix #45 
Test URLs:
- After: https://issue45-improve--clarkcountynv--aemsites.hlx.page/
=> Issue45 improvement on header, tabs animations & subscription ribbon mis alignment in Mobile view

blocks/cards/cards.css
Fix #51 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
- After: https://issue51-cards--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
=> Cards styling based on the site

blocks/map-embed/map-embed.css, blocks/map-embed/map-embed.js
Fix #53 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
- After: https://issue53-map--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
=> Issue53 map

blocks/full-calendar/full-calendar.js, scripts/delayed.js, scripts/utils.js, styles/styles.css, templates/calendar-event/calendar-event.js, templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #47 
Test URLs:
- After: https://issue47-calendarv2--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Calendar Implementation Phase 1 

blocks/cards/cards.css, blocks/cards/cards.js
Fix #58 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
- After: https://issue58-clickable--clarkcountynv--aemsites.hlx.page/drafts/meet/doc1
=> Updating a variant clickable for cards

404.html, blocks/header/header.css, blocks/hero/hero.css, styles/styles.css
Fix #63 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/pagenotfound
- After: https://issue63-404--clarkcountynv--aemsites.aem.page/pagenotfound
=> Instrumenting a custom 404 page for the site 

blocks/map-embed/map-embed.css, styles/styles.css, templates/calendar-event/calendar-event.css, templates/calendar-event/calendar-event.js
Fix #56 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/meet/event-1
- After: https://issue56-calendarv2--clarkcountynv--aemsites.aem.page/drafts/meet/event-1
=> Issue56 calendarv2

helix-query.yaml, styles/styles.css, templates/calendar-event/calendar-event.js, templates/event/event.css, templates/event/event.js
Fix #68 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/meet/event-1
- After: https://issue68-event--clarkcountynv--aemsites.aem.page/drafts/meet/event-1
=> Calendar Event Instrumentation

helix-query.yaml, templates/calendar/calendar.js
Fix #70 
Test URLs:
- After: https://issue70-events--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Updating the logic for events & recurring

helix-query.yaml
Fix #72 
Test URLs:
- After: https://issue72-events--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Adding more helix query

helix-query.yaml, templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #79 
Test URLs:
- After: https://issue79--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Fixing the css issues for calendar implementation

blocks/modal/modal.css, blocks/modal/modal.js, scripts/delayed.js, styles/styles.css, widgets/share-button/share-button.js
Fix #66
Test URLs:
- After: https://issue66-social-share-cards--clarkcountynv--aemsites.aem.page/
=> Issue66 social share cards

blocks/header/header.js, styles/styles.css, templates/agenda/agenda.css, templates/agenda/agenda.js, tools/importer/import-agenda.js, tools/importer/utils.js
Fix #60
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1848
- After: https://issue60-agenda--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1848
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r105
- After: https://issue60-agenda--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r105
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1216
- After: https://issue60-agenda--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1216
=> Implement agenda pages

templates/calendar/calendar.css, templates/calendar/calendar.js, templates/event/event.js
Fix #82 
Test URLs:
- After: https://issue82-modal--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Modal for events Instrumentation on click for Calendar

blocks/hero/hero.css, scripts/scripts.js, styles/styles.css, templates/agenda/agenda.css, tools/importer/import-agenda.js
- Fix styles for mobile view of agenda pages
- Move page title into background image section as it is always on the background image on the website.
Fix #84
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r106
- After: https://issue84-agenda-mobile--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r106
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1332
- After: https://issue84-agenda-mobile--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1332
=> Mobile view for agenda pages + move page title into background section

helix-query.yaml, templates/calendar/calendar.css, templates/calendar/calendar.js, templates/event/event.css, templates/event/event.js
Fix #87 
Test URLs:
- After: https://issue87--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Calendar event footer instrumentation

blocks/columns/columns.js, styles/styles.css
Adds CSS entries and customized column code for business entries and other non-standard pages
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business-detail-t39-r123
- After: https://business-css--clarkcountynv--aemsites.aem.page/business-detail-t39-r123
=> Adds CSS entries and customized column code for business entries and other non-standard pages

blocks/header/header.js
Test URLs:
- After: https://issue83-breadcrumbs-meta-title--clarkcountynv--aemsites.aem.live/
Add to pull from page-title metadata
=> Add logic for breadcrumb from meta

blocks/header/header.js, scripts/scripts.js, tools/importer/import-agenda.js, tools/importer/utils.js
Fix #96 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r106
- After: https://issue96-agenda-page-title--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r106
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1332
- After: https://issue96-agenda-page-title--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1332
=> Use metadata for rendering page title on hero image and breadcrumbs

404.html, styles/styles.css
Fix #98 
Test URLs:
- After: https://issue98-404--clarkcountynv--aemsites.hlx.page/
=> Updating the logic of 404 post recent Code Changes

tools/sidekick/config.json, tools/sidekick/library.html
Fix #44
Test URLs:
- After: https://issue44--clarkcountynv--aemsites.hlx.page/
=> Adding the logic for sidekick library

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #107
Test URLs:
- After: https://issue107--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Adding the logic for read more

styles/styles.css, tools/importer/import-biddetail.js
Fix #114 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/bid-detail/bid-detail-t30-r864
- After: https://issue155-bid-detail-pages--clarkcountynv--aemsites.aem.live/bid-detail/bid-detail-t30-r864
- Before: https://main--clarkcountynv--aemsites.aem.live/bid-detail/bid-detail-t30-r915
- After: https://issue155-bid-detail-pages--clarkcountynv--aemsites.aem.live/bid-detail/bid-detail-t30-r915
=> Implement & Import bid details pages

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #110 
Test URLs:
- After: https://issue110-calendar--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Calendar further improvization

styles/styles.css
Fix #120 
Test URLs:
- After: https://issue120-bug--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Fixing the bug for H3 for "short" behaviour

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #119 
Test URLs:
- After: https://issue119-calendar--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Calendar search form implementation

templates/calendar/calendar.css
Fix #127 
Test URLs:
- After: https://issue127--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Fixing the bugs

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #129 
Test URLs:
- After: https://issue127--clarkcountynv--aemsites.hlx.page/drafts/meet/calendar
=> Calendar Search Implementation

blocks/featured-events/featured-events.css, blocks/featured-events/featured-events.js
Fix #133 
Test URLs:
- After: https://issue133-county-events--clarkcountynv--aemsites.hlx.page/
=> County events featured on Home Page

blocks/featured-events/featured-events.css, blocks/featured-events/featured-events.js, templates/calendar/calendar.js
Fix #135 
Test URLs:
- After: https://issue135-modal--clarkcountynv--aemsites.hlx.page/
=> Count events - Modal instrumentation home page

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #137 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/calendar
- After: https://issue137-bugs--clarkcountynv--aemsites.hlx.page/calendar
=> fixing bugs

blocks/embed/embed.css, blocks/embed/embed.js, blocks/video/video.css, blocks/video/video.js
Fix #139 
Test URLs:
- After: https://issue139-instrument-video--clarkcountynv--aemsites.aem.live/
=> initial checkin-working

blocks/featured-events/featured-events.js, templates/calendar/calendar.js, templates/event/event.js
Fix #141 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.live
- After: https://issue141-bugs--clarkcountynv--aemsites.hlx.live
=> Fixing bugs of displaying ICS + Close

templates/calendar/calendar.js
Fix #143 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/calendar
- After: https://issue143--clarkcountynv--aemsites.hlx.page/calendar
=> Enabling List monthly

blocks/featured-events/featured-events.js, templates/calendar/calendar.js
Fix #145 
Test URLs:
- After: https://issue145--clarkcountynv--aemsites.hlx.live/calendar
=> Calendar featured implementation from the calendar panel

helix-query.yaml, templates/calendar/calendar.js
Fix #147 
Test URLs:
- After: https://issue147-exclude--clarkcountynv--aemsites.hlx.page/
=> Adding logic of excluding dates

templates/calendar/calendar.js
Fix #149 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/calendar
- After: https://issue-149-exclude--clarkcountynv--aemsites.hlx.page/calendar
=> Adding an additional library for excluded dates

fstab.yaml, helix-query.yaml
Fix #152 
Test URLs:
- After: https://issue152--clarkcountynv--aemsites.hlx.live/calendar
=> Updating the helix and fstab

blocks/featured-events/featured-events.js, templates/calendar/calendar.js
Fix #154 
Test URLs:
- After: https://issue154--clarkcountynv--aemsites.hlx.live/calendar
=> Calendar Improvisation - allotting URL's to individual departments calendar

templates/calendar/calendar.js
Fix #156 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.hlx.page/calendar
- After: https://issue156--clarkcountynv--aemsites.hlx.page/calendar
=> Updating the logic for having individual URLs for child calendars

scripts/delayed.js, templates/calendar/calendar.js
Fix #160 
Test URLs:
- After: https://issue160--clarkcountynv--aemsites.hlx.live/calendar
=> Improvising Page performance of the master calendar

styles/styles.css, templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #162 
Test URLs:
- After: https://issue162-spinner--clarkcountynv--aemsites.hlx.live/calendar
=> Issue162 spinner implementation while calendar is loading

blocks/header/header.js, styles/styles.css, tools/importer/import-news.js, tools/importer/utils.js
Fix #113 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r967
- After: https://issue113-news-pages--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r967
- Before: https://main--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r494
- After: https://issue113-news-pages--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r494
- Before: https://main--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r977
- After: https://issue113-news-pages--clarkcountynv--aemsites.aem.live/news/news-detail-t28-r977
=> Design and importer for news pages

blocks/header/header.css, blocks/header/header.js, scripts/scripts.js, styles/styles.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1066
- After: https://issue88-bcrumbs--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1066
- Before: https://main--clarkcountynv--aemsites.aem.page/agenda/agenda-detail-t43-r1219
- After: https://issue88-bcrumbs--clarkcountynv--aemsites.aem.page/agenda/agenda-detail-t43-r1219
=> Move breadcrumbs inside hero background

tools/importer/import-agenda.js
Included URLs having bugs discovered in UAT. 
Fix #166
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1859
- After: https://issue166-agenda-fixes--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1859
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1895
- After: https://issue166-agenda-fixes--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r1895
- Before: https://main--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r2159
- After: https://issue166-agenda-fixes--clarkcountynv--aemsites.aem.live/agenda/agenda-detail-t43-r2159
=> @fix: Agenda page breadcrumbs and audio/video links

blocks/accordion-ml/accordion-ml.css, blocks/accordion-ml/accordion-ml.js
Fix #170 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/
- After: https://issue170-bug--clarkcountynv--aemsites.aem.live/government/departments/
=> Issue170 bug - Breadcrumbs causing issues to the Mobile view of accordion - ml

blocks/accordion-ml/accordion-ml.js, blocks/header/header.js
Fix #181 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live
- After: https://issue181-bugs--clarkcountynv--aemsites.aem.live
=> Fixing the bugs in accordion - ml

blocks/accordion-ml/accordion-ml.js, blocks/accordion/accordion.css, blocks/accordion/accordion.js
Fix #173
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/division_of_air_quality/monitoring/
- After: https://issue173-accordion-qna--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/division_of_air_quality/monitoring/
=> FAQ Accordion block implementation

blocks/embed/embed.css, blocks/embed/embed.js
Fix #185 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/foster_care/foster-care-information-session-signup
- After: https://issue185--clarkcountynv--aemsites.aem.live/residents/family_services/foster_care/foster-care-information-session-signup
=> Adding code for iframe forms

styles/styles.css
Fix #189 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/foster_care/foster-care-information-session-signup
- After: https://issue189-bugs--clarkcountynv--aemsites.aem.live/residents/family_services/foster_care/foster-care-information-session-signup
=> Fixing the bug of page title not getting displayed on desktop & on mobile - its at the very top

styles/styles.css, tools/importer/import-leftnav.js, tools/importer/utils.js
=> Improve importer script to download PDFs and fixed location

blocks/featured-events/featured-events.js
Fix #193 
Test URLs:
- After: https://issue193--clarkcountynv--aemsites.aem.live/
=> fixing the bug

tools/importer/utils.js
=> Fix download path and links of imported file

helix-query.yaml
Fix #200 
Test URLs:
- After: https://issue200--clarkcountynv--aemsites.aem.live/calendar
=> Updating the helix-query based on the improvizations on calendar

blocks/accordion-ml/accordion-ml.css, blocks/accordion-ml/accordion-ml.js, blocks/leftnav-info/leftnav-info.css, blocks/leftnav-info/leftnav-info.js, tools/importer/import-leftnav.js
Fix #165 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/akasjain/infocardmonitoring
- After: https://issue165-leftnav-extensions--clarkcountynv--aemsites.aem.live/drafts/akasjain/infocardmonitoring
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/
- After: https://issue165-leftnav-extensions--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/
=> Instrument for Hours and contact info in left section

blocks/featured-events/featured-events.js, helix-query.yaml, templates/calendar/calendar.css, templates/calendar/calendar.js, templates/event/event.js
Fix #195 
Test URLs:
- After: https://issue195--clarkcountynv--aemsites.aem.live/calendar
=> Calendar Improvization

blocks/table/table.css, blocks/table/table.js
Fix #205 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/klivings/table-test
- After: https://issue205-default-table--clarkcountynv--aemsites.aem.live/drafts/klivings/table-test
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/district_attorney/divisions/family_support_division/payments
- After: https://issue205-default-table--clarkcountynv--aemsites.aem.page/government/departments/district_attorney/divisions/family_support_division/payments
=> add default table

tools/importer/import-leftnav.js
=> Importer for iframe based form

tools/importer/import-leftnav.js
Fix #203
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/akasjain/infocardmonitoring
- After: https://importer-leftnav-cards--clarkcountynv--aemsites.aem.live/drafts/akasjain/infocardmonitoring
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/
- After: https://importer-leftnav-cards--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/
=> Importer for leftnav cards - contact and hours

templates/event/event.js
Fix #209 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar/county-commission-district-a/event-5
- After: https://issue209--clarkcountynv--aemsites.aem.live/calendar/county-commission-district-a/event-5
=> Adding the default logo to the calendar events

blocks/featured-events/featured-events.js, templates/event/event.js
Fix #211 
Test URLs:
- After: https://issue209--clarkcountynv--aemsites.aem.live/
=> Default image for featured card on the Home page

scripts/scripts.js, scripts/utils.js, templates/calendar/calendar.css
Fix #213 
Test URLs:
- After: https://issue213--clarkcountynv--aemsites.aem.live/calendar
=> Calendar further improvements

blocks/cards/cards.css, blocks/cards/cards.js, tools/importer/import-leftnav.js, tools/importer/utils.js
Fix #174 
Test URLs:
- Original: https://www.clarkcountynv.gov/government/board_of_county_commissioners/district_a/index.php
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/
- After: https://issue174-cards-focus-2--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/
=> Implement & import card block variant - tiles

blocks/banner-carousel/banner-carousel.css
Fix #220 
Test URLs:
- After: https://issue220--clarkcountynv--aemsites.aem.live/calendar
=> Carousel impacting the calendar search functionality

templates/calendar/calendar.css
Fix #224 
Test URLs:
- After: https://issue224-css--clarkcountynv--aemsites.aem.live/calendar
=> Fixing the colours

tools/importer/import-agenda.js, tools/importer/import-biddetail.js, tools/importer/import-leftnav.js, tools/importer/import-news.js, tools/importer/utils.js
Fix #221
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/disclosure-statements
- After: https://issue221-pdf-redirect--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/disclosure-statements
=> Create redirect for all PDF files

styles/styles.css
Fix #229
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/county_managers_office/biographies/abigail-frierson-deputy-county-manager
- After: https://issue229--clarkcountynv--aemsites.aem.live/government/county_managers_office/biographies/abigail-frierson-deputy-county-manager
=> Bringing in a behaviour for biography

blocks/banner-carousel/banner-carousel.css, styles/styles.css, templates/default/default.css
Fix #232 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/county_managers_office/ombudsman/complaint-forms
- After: https://issue232--clarkcountynv--aemsites.aem.live/government/county_managers_office/ombudsman/complaint-forms
=> Adding a behaviour on buttons

blocks/banner-carousel/banner-carousel.css, blocks/cards/cards.css, blocks/cards/cards.js, styles/styles.css, templates/default/default.css, tools/importer/import-leftnav.js, tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/contact-us
- After: https://meet-team-style--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/contact-us
=> Styling changes for Meet the Team pages

scripts/scripts.js
Fix #236 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/srcc-planning
- After: https://breadcrumbs-fix--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/srcc-planning
=> Fix breadcrumbs title

blocks/cards/cards.css, blocks/cards/cards.js, tools/importer/import-leftnav.js
Fix #240
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/county_managers_office/biographies/
- After: https://issue240-importer-cards-staff--clarkcountynv--aemsites.aem.page/government/county_managers_office/biographies/
=> Importer for cards staff variant + youtube support

tools/importer/import-leftnav.js, tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/county_managers_office/biographies/
- After: https://importer-fix--clarkcountynv--aemsites.aem.page/government/county_managers_office/biographies/
=> @fix: importer

tools/importer/import-leftnav.js, tools/importer/utils.js
=> Importer : Pages without leftnav should not error out

blocks/accordion/accordion.css, blocks/table/table.css, styles/styles.css, templates/default/default.css, tools/importer/import-leftnav.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_programs/community_resources_management/private-activity-bonds
- After: https://styling-fixes--clarkcountynv--aemsites.aem.page/residents/assistance_programs/community_resources_management/private-activity-bonds
=> Styling fixes for residents pages + some generic styles

blocks/cards/cards.css, blocks/cards/cards.js, blocks/text/text.css, styles/styles.css
Fix #252 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/constable/constable_las_vegas_township/deputy-constable-contract-employment-opportunities
- After: https://issue252--clarkcountynv--aemsites.aem.live/government/departments/constable/constable_las_vegas_township/deputy-constable-contract-employment-opportunities
=> Adding a behaviour on clickable-images

blocks/embed/embed.css, blocks/table/table.css, blocks/text/text.css, styles/styles.css, templates/default/default.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_programs/
- After: https://issue254--clarkcountynv--aemsites.aem.page/residents/assistance_programs/
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_programs/partner-with-us
- After: https://issue254--clarkcountynv--aemsites.aem.page/residents/assistance_programs/partner-with-us
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_programs/senior-services
- After: https://issue254--clarkcountynv--aemsites.aem.page/residents/assistance_programs/senior-services
=> Colored text styling + table styles found in residents pages

templates/event/event.css, templates/event/event.js
Fix #256 
Test URLs:
- After: https://issue256--clarkcountynv--aemsites.aem.live/calendar
=> Adding a function to consider a link for hero image for events

blocks/cards/cards.css, blocks/cards/cards.js, blocks/columns/columns.js
Fix #258 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/meet/doc1
- After: https://issue258--clarkcountynv--aemsites.aem.page/drafts/meet/doc1
=> Enable Image links for cards block all variants - clickable, clickable-images, staff, tiles along with columns block

tools/importer/import-agenda.js, tools/importer/import-biddetail.js, tools/importer/import-leftnav.js, tools/importer/import-news.js, tools/importer/utils.js
Fix #260
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/residents/assistance_programs/adult-care-services
- After: https://issue260-pdf-download--clarkcountynv--aemsites.aem.page/drafts/akasjain/residents/assistance_programs/adult-care-services
=> Importer - PDF and docx file download to page based path

tools/sidekick/config.json
Fix #263 
Test URLs:
- After: https://issue263-assetlibrary--clarkcountynv--aemsites.aem.live/
=> Adding asset library pluggin

blocks/cards/cards.js, blocks/columns/columns.js, templates/default/default.js, tools/importer/import-leftnav.js, tools/importer/utils.js
Fix #261 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/board_of_county_commissioners/district_e/biography
- After: https://issue261-image-download--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/board_of_county_commissioners/district_e/biography
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/departments/
- After: https://issue261-image-download--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/departments/
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/board_of_county_commissioners/
- After: …
=> Importer - Download images to a page based path and saved as link in markdown

blocks/cards/cards.js
Fix #272
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/board_of_county_commissioners/district_a/
- After: https://issue272--clarkcountynv--aemsites.aem.page/drafts/akasjain/government/board_of_county_commissioners/district_a/
=> @fix : Handle already created picture element in cards block

blocks/document-center/document-center.css, blocks/document-center/document-center.js
Fix #176 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_e/newsletters
- After: https://issue176-document-center--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_e/newsletters
=> feat: Implement document centre block for newsletters

blocks/text/text.css, styles/styles.css, templates/default/default.css, tools/importer/import-news.js, tools/importer/utils.js, tools/sidekick/config.json
Fix #254 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1029
- After: https://issue254--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1029
=> Issue254 : Colored text styling + image fixes in importer for news page

tools/importer/import-leftnav.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/newsletter
- After: https://importer-doc-center--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_a/newsletter
=> Importer for document center block

blocks/cards/cards.css, blocks/table/table.css
Fix #279
Test URLs:
- Original link: https://www.clarkcountynv.gov/government/board_of_county_commissioners/district_g/district_announcements.php
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_g/district-announcements-1
- After: https://issue279-colored-table--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/district_g/district-announcements-1
=> feat: Colored table variant

blocks/cards/cards.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/henderson/divisions/
- After: https://cards-fix--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/henderson/divisions/
=> @fix : clickable cards rendering

404.html, styles/styles.css
Fix #289 
Test URLs:
- After: https://issue289-404--clarkcountynv--aemsites.aem.live/
=> Fixing the 404 page

styles/styles.css, templates/default/default.css, templates/default/default.js
Fix #293
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/meet/
- After: https://issue293--clarkcountynv--aemsites.aem.live/drafts/meet/
=> Apply CSS to specific words 

blocks/table/table.css, tools/importer/utils.js
Fix #250
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/administrative_services/rural_alliance_advisory_committee/meeting-agendas
- After: https://issue250-agenda-table--clarkcountynv--aemsites.aem.page/government/departments/administrative_services/rural_alliance_advisory_committee/meeting-agendas
=> feat: Agenda table variant

blocks/hotline/hotline.css, blocks/hotline/hotline.js
Fix #297 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/tpop-contracted-providers
- After: https://issue297-hotlines-search--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/tpop-contracted-providers
=> feat: Search functionality in hotlines block

blocks/table/table.css
Fix #300 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/cjcc/
- After: https://issue300--clarkcountynv--aemsites.aem.live/government/cjcc/
=> Adding more colors for the tables

blocks/table/table.css, tools/importer/import-leftnav.js, tools/importer/utils.js
Fix #303 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/cjcc/cjcc-meetings
- After: https://issue303-importer-agenda-table--clarkcountynv--aemsites.aem.page/government/cjcc/cjcc-meetings
=> feat: Add importer support for agenda list pages

tools/importer/import-leftnav.js, tools/importer/utils.js
1. Remove garbled characters from breadcrumbs
2. Multiple clickable cards on a page
3. Handle case sensitiveness in audio/video files mp3 / MP3
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/announcements
- After: https://importer-fixes--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/announcements
=> fix : Importer enhancements

templates/default/default.css
Fix #309 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/comprehensive_planning_department/library/title-30
- After: https://issue309--clarkcountynv--aemsites.aem.page/government/departments/comprehensive_planning_department/library/title-30
=> Adding image - center behaviour

blocks/center/center.css
Fix #313 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/constable/divisions/constable_mesquite_township/
- After: https://issue313--clarkcountynv--aemsites.aem.live/government/departments/constable/divisions/constable_mesquite_township/
=> Removing image - center behaviour

blocks/cards/cards.css, blocks/cards/cards.js, blocks/table/table.css, templates/default/default.css, templates/default/default.js, templates/full/full.js, tools/importer/import-leftnav.js, tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/
- After: https://minor-fixes--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/
=> fix: Styling fixes for parks pages

tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/facilities/
- After: https://importer-fix--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/facilities/
=> fix: Importer fix for pages with index.php

styles/styles.css
Fix #322
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/desert_conservation_program/biennial-amp-reports
- After: https://issue322--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/desert_conservation_program/biennial-amp-reports
=> fixing the css

blocks/cards/cards.css, blocks/text/text.css, templates/default/default.css, tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/parks___trails/
- After: https://fix-links-path--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/parks___trails/
=> fix: fix link for index.jsp pages

blocks/cards/cards.css, blocks/table/table.css, blocks/text/text.css, styles/styles.css, templates/default/default.css, templates/full/full.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/seniors_centers/winchester_dondero_cultural_center/meeting-rooms
- After: https://styling-parks-pages--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/seniors_centers/winchester_dondero_cultural_center/meeting-rooms
=> Styling parks pages

blocks/cards/cards.css, blocks/table/table.css, styles/styles.css, templates/default/default.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/pools___aquatic/hollywood_aquatic_center/hollywood-indoor-pool
- After: https://styling-fixes--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/pools___aquatic/hollywood_aquatic_center/hollywood-indoor-pool
=> feat: Styling for parks pages

blocks/cards/cards.css
Fix #329 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/public_art/galleries/winchester_gallery/winchester_past_exhibits/grlrm-collective
- After: https://issue329--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/public_art/galleries/winchester_gallery/winchester_past_exhibits/grlrm-collective
=> Adding a behavior for multiple images which are NOT clickable 

tools/importer/utils.js
Fix #331 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/public_art/projects/zap!_neighborhood_art/index.php
- After: https://issue331--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/services/public_art/projects/zap_neighborhood_art/
=> Updating Importer to remove "!" as well from the path links 

blocks/cards/cards.css, blocks/table/table.css
Fix #335
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/teen-programs-desert-breeze
- After: https://issue355-cardssizing--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/teen-programs-desert-breeze
=> issue355-cardssizing

blocks/table/table.css, templates/default/default.css
Fix #340 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/audit_department/audit-committee
- After: https://issue340--clarkcountynv--aemsites.aem.live/government/departments/audit_department/audit-committee
=> Table styling

blocks/table/table.css, styles/styles.css, templates/default/default.css, templates/default/default.js
Fix #352 
https://www.clarkcountynv.gov/government/american_rescue_plan_act/index.php
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/american_rescue_plan_act/
- After: https://issue352--clarkcountynv--aemsites.aem.live/government/american_rescue_plan_act/
=> Decorating links with mentioning classes like - Take the survey [class: button default] 

blocks/cards/cards.css
Fix #358 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/new-independent-living
- After: https://issue358--clarkcountynv--aemsites.aem.live/residents/family_services/new-independent-living
=> Enablement of biography on clickable images

tools/importer/utils.js
Fix #362 
www.clarkcountynv.gov/residents/family_services/services/case_management.php
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/services/case-management
- After: https://issue362--clarkcountynv--aemsites.aem.live/residents/family_services/services/case-management
=> Fixing few issues with Importer for couple of pages

blocks/cards/cards.css, blocks/text/text.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/facilities/camp-lee-canyon
- After: https://new-styling--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/facilities/camp-lee-canyon
=> feat: Styling for family services pages

blocks/cards/cards.css, blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_programs/housing-expense-assistance
- After: https://cards-styling--clarkcountynv--aemsites.aem.page/residents/assistance_programs/housing-expense-assistance
=> Cards styling

blocks/carousel/carousel.js
Fix #373 
Test URLs:
- After: https://issue373--clarkcountynv--aemsites.aem.live/
=> Fixing the Image links for carousel

templates/default/default.js
Fix #375 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/meet/specdist-gid
- After: https://issue375--clarkcountynv--aemsites.aem.page/drafts/meet/specdist-gid
=> Enablement of special words more than 3 within a "p" element

templates/calendar/calendar.js
Fix #381 
Test URLs:
- After: https://issue381--clarkcountynv--aemsites.aem.live/calendar
=> Fixing the text color of individual departments for the calendar implementation

templates/calendar/calendar.js
Fix #385 
Test URLs:
- After: https://issue385--clarkcountynv--aemsites.aem.live/calendar
=> Calendar deep links Implementation 

templates/calendar/calendar.js, templates/event/event.css, templates/event/event.js
Fix #391 
Test URLs:
- After: https://issue391--clarkcountynv--aemsites.aem.live/calendar
=> Customizing the Right Click calendar events based on the readmore options

templates/calendar/calendar.js
Fix #395 
Test URLs:
- After: https://issue395--clarkcountynv--aemsites.aem.live/calendar
=> Enablement of event ID's for the calendar events which can be shared

templates/calendar/calendar.js
Fix #406 
Test URLs:
- After: https://issue406--clarkcountynv--aemsites.aem.live/calendar
=> Enabling prev and next buttons impact on deep links

blocks/banner-carousel/banner-carousel.js
Fix #410 
Test URLs:
- After: https://issue410--clarkcountynv--aemsites.aem.live/calendar
=> Fixing the Carousal banner for Image Links

blocks/cards/cards.css, blocks/hotline/hotline.js, blocks/map-embed/map-embed.css, blocks/text/text.css, styles/styles.css, templates/full/full.css
Fix #408
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/tpop-contracted-providers
- After: https://new-styles--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/tpop-contracted-providers
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/elections/all_elected_officials/state
- After: https://new-styles--clarkcountynv--aemsites.aem.page/government/departments/elections/all_elected_officials/state
=> feat : Add new styles

blocks/text/text.css, blocks/video/video.css
…edded videos. allows for aligned titles to be added above videos
Test URLs:
- Before: hhttps://main--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/video-library
- After: https://css-updates--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/video-library
=> Issue 402 - Styling for video listing pages

blocks/embed/embed.js, blocks/header/header.css, blocks/header/header.js
Fix #384 
Test URLs:
- After: https://issue384-search--clarkcountynv--aemsites.aem.live/
=> Search Implementation Part 1 - Layout of the Search Box

blocks/faq-accordion/faq-accordion.css, blocks/faq-accordion/faq-accordion.js, styles/styles.css
Fix #179 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/faq
- After: https://faq-accordion--clarkcountynv--aemsites.aem.page/drafts/akasjain/faq
=> feat : Multilevel faq accordion

blocks/header/header.css
Fix #416 
Test URLs:
- After: https://issue416--clarkcountynv--aemsites.aem.live/
=> Search Mobile view instrumentation

styles/styles.css, templates/default/default.css
Fix #422 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/klivings/purple-special-words
- After: https://issue422-Special-words-more-colors--clarkcountynv--aemsites.aem.live/drafts/klivings/purple-special-words
=> add css color purple special words

blocks/faq-accordion/faq-accordion.js, tools/importer/import-leftnav.js
Fix #420
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/business_license_audit/faq
- After: https://faq-accordion-importer--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/business_license_audit/faq
=> feat: Importer for multilevel faq accordion

helix-query.yaml, scripts/article-list.js, templates/news-list/news-list.js
This PR is to add changes to the helix-query.yaml file and the basic building blocks and code for the new list page.
Since the yaml file needs to be on the main branch to test, I'm placing the basics into the same branch together to merge, after which any customization or updates can be made once indexing and functionality is verified
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/
- After: https://article-list--clarkcountynv--aemsites.aem.page
=> News list basic functionality

blocks/header/header.css, blocks/header/header.js, scripts/utils.js
Fix #424 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live
- After: https://issue424--clarkcountynv--aemsites.aem.live
=> Search Functionality Instrumentation of Tabs 

blocks/banner-carousel/banner-carousel.css
Fix #431 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/elected_officials/county_clerk/press
- After: https://issue431--clarkcountynv--aemsites.aem.page/government/elected_officials/county_clerk/press
=> Bug with banner carousal

blocks/cards/cards.css, blocks/text/text.css, styles/styles.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/drivers-independent-contractors
- After: https://contractors-styles--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/drivers-independent-contractors
=> styles updates for independent contractors page

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1057
- After: https://yaml-updates0227--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1057
=> yaml updates to correct value attribute importation

blocks/table/table.css, blocks/text/text.css
Fix #430 
Test URLs:
- Before: https://issue430-text-css-fixes--clarkcountynv--aemsites.aem.live/government/departments/fire/swimming-pools
- After: https://main--clarkcountynv--aemsites.aem.live/government/departments/fire/swimming-pools
=> text - table css fixes

blocks/header/header.js
Fix #433 
Test URLs:
- After: https://issue433--clarkcountynv--aemsites.aem.live/
=> Finalyzing the search functionality

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
- After: https://helix-query-updates-0228--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
=> minor case corrections to metadata titles in helix-query file

styles/styles.css
Fix #442 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/top_services/faqs/mobile-application-support
- After: https://issue442--clarkcountynv--aemsites.aem.page/top_services/faqs/mobile-application-support
=> Fixing the bug with Hero 

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
- After: https://yaml-update3--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
=> adds url entry to news properties

blocks/spacer/spacer.css, blocks/spacer/spacer.js, blocks/table/table.css, styles/styles.css, templates/default/default.css, templates/default/default.js
Fix #444 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/desert_conservation_program/contact-us
- After: https://issue444--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/desert_conservation_program/contact-us
=> Fixing the contact - us page along with adding a spacer block

blocks/toc/toc.css, blocks/toc/toc.js, scripts/scripts.js, scripts/utils.js, styles/styles.css, templates/default/default.css, templates/default/default.js
Fix #449 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/meet/symposia
- After: https://issue449--clarkcountynv--aemsites.aem.live/drafts/meet/symposia
=> Adding TOC Horizontal block & top arrow

blocks/featured-events/featured-events.css, blocks/featured-events/featured-events.js, blocks/hero/hero.css, templates/event/event.js
Fix #451 
Test URLs:
- After: https://issue451--clarkcountynv--aemsites.aem.live/
=> HomePage 'see more' HERO buttons, Allowing only 4 latest items for featured events

blocks/carousel/carousel.css, blocks/columns/columns.css, blocks/columns/columns.js, blocks/featured-events/featured-events.css, styles/styles.css
Fix #453 
Test URLs:
- After: https://issue453--clarkcountynv--aemsites.aem.live/
=> Enable Highlight Column on home page - enabling YT videos with custom Image with Play Button + Carousal styling Improvisations

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
- After: https://helix-query-updates-030325--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
=> Corrections to helix-query.yaml

blocks/cards/cards.css
Fix #472 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/shooting_complex/event-planning-tool-kit
- After: https://issue472-add-more-sizes-cards-images--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/shooting_complex/event-planning-tool-kit
=> add more cards image sizes

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
- After: https://yamlupdates3325--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1002
=> removing hyphens as they are causing issues in the news list js

blocks/columns/columns.js
Fix #457 
Test URLs:
- After: https://issue457--clarkcountynv--aemsites.aem.live/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/press
- After: https://issue457--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/press
=> Adding clickable image behavior to columns

blocks/map-embed/map-embed.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business-detail/business-detail-t39-r175
- After: https://map-embed-business030425--clarkcountynv--aemsites.aem.live/business-detail/business-detail-t39-r175
=> Making corrections to mab embed custom classes for business detail pages

blocks/cards/cards.css
Fix #525 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/departments/district_attorney/divisions/family_support_division/
- After: https://issue525--clarkcountynv--aemsites.aem.live/departments/district_attorney/divisions/family_support_division/
=> Adding behavior for large clickable images

blocks/cards/cards.css, styles/styles.css, templates/default/default.css
Fix #479 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/fire/ccfd-history-the-1960s
- After: https://issue479-cards-more-images-sizes--clarkcountynv--aemsites.aem.live/government/departments/fire/ccfd-history-the-1960s
=> add more cards text colors sizes

blocks/cards/cards.css, templates/default/default.js
Fix #551 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/finance/financial_reporting/budget/
- After: https://issue551--clarkcountynv--aemsites.aem.live/government/departments/finance/financial_reporting/budget/
=> Adding logic for h3 special and clickable

blocks/text/text.css, styles/styles.css, templates/default/default.css
Fix #541 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/fire/el-rancho-hotel-fire
- After: https://issue541-add-text-cards-styles--clarkcountynv--aemsites.aem.live/government/departments/fire/el-rancho-hotel-fire
=> add more styles for text, cards

blocks/table/table.css, styles/styles.css
Fix #563 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/ccabmw-meeting-11-11-2020
- After: https://issue563--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/ccabmw-meeting-11-11-2020
=> Adding logic for table head color

tools/importer/import-leftnav.js, tools/importer/utils.js
Test URLs:
- Original Page: https://www.clarkcountynv.gov/residents/truancy_prevention_outreach_program/hotlines.php
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/hotlines
- After: https://hotlines-block-importer--clarkcountynv--aemsites.aem.page/residents/truancy_prevention_outreach_program/hotlines
=> feat: Importer for hotlines block

blocks/cards/cards.js, blocks/text/text.css, templates/default/default.css, tools/importer/import-leftnav.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/justice_courts/jurisdictions/bunkerville/
- After: https://misc-styling--clarkcountynv--aemsites.aem.live/government/departments/justice_courts/jurisdictions/bunkerville/
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/henderson/about-us
- After: https://misc-styling--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/henderson/about-us
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/g …
=> feat: Add styles

blocks/cards/cards.css, blocks/cards/cards.js, blocks/embed/embed.css, blocks/embed/embed.js, blocks/table/table.css, templates/default/default.css, tools/importer/import-leftnav.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/seniors_centers/whitney_recreation____senior_center/whitney_recreation_center/facility-reservations
- After: https://cards-text-variant--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/seniors_centers/whitney_recreation____senior_center/whitney_recreation_center/facility-reservations
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/
- After: https://cards-text-variant--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/ …
=> fix : Add variation to clickable cards to have text top or text bottom with flexibile image alignment

templates/default/default.js
Fix #601 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/main-office
- After: https://issue601--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/main-office
=> Fixing the console error messages

templates/default/default.js, tools/importer/import-leftnav.js
Fix #172 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/county_managers_office/ombudsman/reports2
- After: https://issue172--clarkcountynv--aemsites.aem.live/government/county_managers_office/ombudsman/reports2
=> Fixing the trim error message for null nodevalue

blocks/cards/cards.css
Fix #600 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/wetlands_park/wetlandswalkers
- After: https://issue600-add-width-height-cards--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/wetlands_park/wetlandswalkers
=> add more cards width, height

blocks/table/table.css, blocks/text/text.css, blocks/video/video.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/district_d/mccurdy-on-the-move
- After: https://styling-changes--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/district_d/mccurdy-on-the-move
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_public_adminstrator/securing-property-before-court
- After: https://styling-changes--clarkcountynv--aemsites.aem.live/government/elected_officials/county_public_adminstrator/securing-property-before-court
- Before: …
=> Styles update

blocks/video/video.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/copper-wire-theft
- After: https://issue653-add-embed-sizing--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/copper-wire-theft
=> add video sizes

templates/calendar/calendar.js, templates/event/event.css, templates/event/event.js
Fix #654 
Test URLs:
- After: https://issue654--clarkcountynv--aemsites.aem.live/calendar
=> Fixing all console error messages for Calendar along with enabling single exclude dates

templates/default/default.css
Fix #570 
Test URLs:
- Before: http://main--clarkcountynv--aemsites.aem.live/residents/assistance_programs/suicide-prevention-services
- After: http://issue570--clarkcountynv--aemsites.aem.live/residents/assistance_programs/suicide-prevention-services
=> Adding a font behaviour

blocks/columns/columns.css, blocks/table/table.css, styles/styles.css
Fix #812 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/administrative_services/rural_alliance_advisory_committee/
- After: https://issue812--clarkcountynv--aemsites.aem.live/government/departments/administrative_services/rural_alliance_advisory_committee/
=> Improvising Alert block

templates/default/default.css, tools/importer/utils.js
Test URLs:
- Original: https://www.clarkcountynv.gov/government/departments/public_works_department/vector_control.php
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/public_works_department/vector-control
- After: https://new-styles--clarkcountynv--aemsites.aem.page/government/departments/public_works_department/vector-control
=> Add style for text highlight in sentence + importer

blocks/map-embed/map-embed.css, blocks/map-embed/map-embed.js, blocks/table/table.css, blocks/text/text.css, templates/default/default.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/main-office
- After: https://table-style--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/main-office
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/contact-us
- After: https://table-style--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/contact-us
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk …
=> Add table style

blocks/columns/columns.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/chambers-of-commerce
- After: https://columns-style-wedding--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/chambers-of-commerce
=> Add styles for wedding footer pages

blocks/cards/cards.css, blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/north_las_vegas/efile
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/justice_courts/jurisdictions/north_las_vegas/efile
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/human_resources/office_of_diversity_division/sec_504_ada_title_ii/504-department-liaisons
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/human_resources/office_of_diversity_division/sec_504_ada_title_ii/504-department-liaisons
=> Align PDF clickble cards

blocks/accordion/accordion.js, styles/styles.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/business-detail/business-detail-t39-r143
- After: https://icon-style--clarkcountynv--aemsites.aem.page/business-detail/business-detail-t39-r143
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/general_business/faq-general-business
- After: https://icon-style--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/general_business/faq-general-business
=> Icon styles for business detail pages

blocks/embed/embed.css, blocks/embed/embed.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/foster-home-licensing
- After: https://iframe-form-style--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/foster-home-licensing
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/elections/tagalog/
- After: https://iframe-form-style--clarkcountynv--aemsites.aem.live/government/departments/elections/tagalog/
=> Add style to allow googleform scrolling

blocks/cards/cards.js, blocks/table/table.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/human_resources/employment/
- After: https://card-open-new-tab--clarkcountynv--aemsites.aem.page/government/departments/human_resources/employment/
=> In clickable cards, open external links in new tab

blocks/table/table.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/fire/fire-prevention
- After: https://table-2col-colspan--clarkcountynv--aemsites.aem.page/government/departments/fire/fire-prevention
=> Enhance table block to support colspan for 2 column tables

blocks/accordion/accordion.css, blocks/hotline/hotline.css, blocks/hotline/hotline.js, blocks/map-embed/map-embed.css, templates/default/default.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/truancy_prevention_outreach_program/hotlines
- After: https://hotlines-sorting--clarkcountynv--aemsites.aem.live/residents/truancy_prevention_outreach_program/hotlines
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/justice_courts/jurisdictions/henderson/divisions/evictions/
- After: https://hotlines-sorting--clarkcountynv--aemsites.aem.live/government/departments/justice_courts/jurisdictions/henderson/divisions/evictions/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/justice_courts/jur …
=> Sort categories in hotline block alphabetically

blocks/accordion/accordion.css, blocks/text/text.css, tools/importer/import-leftnav.js, tools/importer/utils.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/administrative_services/animal_protection_services/faqs
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/administrative_services/animal_protection_services/faqs
=> Add new styles based on page requirement

helix-query.yaml
Fix #985 
Test URLs:
- After: https://issue985--clarkcountynv--aemsites.aem.live/
=> Adding freq to events

templates/calendar/calendar.js
Fix #966 
Test URLs:
- After: https://issue966--clarkcountynv--aemsites.aem.live/calendar
=> Calendar monthly - N no. of weekday functionality enablement

templates/calendar/calendar.js
Fix #1003 
Test URLs:
- After: https://issue1003-calendar--clarkcountynv--aemsites.aem.live/calendar
=> Adding the new feature of Grouping divisions for a recurring calendar

blocks/accordion/accordion.css, blocks/map-embed/map-embed.css, blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/elections/22g-info
- After: https://accordion-font-size--clarkcountynv--aemsites.aem.page/government/departments/elections/22g-info
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/comprehensive_planning_department/boards_and_commissions/planning-commissioners
- After: https://accordion-font-size--clarkcountynv--aemsites.aem.page/government/departments/comprehensive_planning_department/boards_and_commissions/planning-commissioners
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/assistance_ …
=> Fix font style in accordion item content

blocks/document-center/document-center.css, blocks/document-center/document-center.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/risk_management/employee-and-retiree-health-benefits
- After: https://document-center-text--clarkcountynv--aemsites.aem.page/government/departments/risk_management/employee-and-retiree-health-benefits
=> Add support for additional text in document center file group

styles/styles.css, templates/default/default.css
Fix #1012 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/memorial-development-process
- After: https://issue1012--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/memorial-development-process
=> Adding parks-purple special color

blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/customer-comments
- After: https://new-style--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/customer-comments
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/fire/community-events-station-tours
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/fire/community-events-station-tours
=> Add style for additional padding to table cell

blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/human_resources/about_human_resources/bargaining-contracts
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/human_resources/about_human_resources/bargaining-contracts
- Before: https://main--clarkcountynv--aemsites.aem.live/business/business_opportunities/current-opportunities
- After: https://new-style--clarkcountynv--aemsites.aem.live/business/business_opportunities/current-opportunities
=> First table column align center

templates/default/default.css
Fix #1022 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/jcj-architecture
- After: https://issue1022--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/jcj-architecture
=> Adding no underline behavior

blocks/table/table.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/public_works_department/
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/public_works_department/
=> Add table styles - same width column, thick border

blocks/text/text.css
Fix #1001 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/
- After: https://issue1001-css-cards-buttons--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/
=> add more text color css

blocks/table/table.css, templates/default/default.js
Fix #1027 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/timeline-upcoming-events
- After: https://issue1027--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/1_october_memorial/timeline-upcoming-events
=> Parks table enablement plus special words for h4, h5 and h6

scripts/scripts.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/
- After: https://issue-305--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/
=> Stay Connected Modal for Parks & Recreation Department

scripts/scripts.js, styles/styles.css
Fix #413 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/divisions/business_license_audit/faq
- After: https://issue-413--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/divisions/business_license_audit/faq
=> Hero Headline Should be H1 Tag (sitewide)

blocks/cards/cards.css, blocks/text/text.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/wetlands_park/about_us/trails-trailheads
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/wetlands_park/about_us/trails-trailheads
- Before: https://main--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/shooting_complex/special-events
- After: https://new-style--clarkcountynv--aemsites.aem.page/government/departments/parks___recreation/shooting_complex/special-events
=> Add style to align text to right

blocks/accordion/accordion.css, blocks/accordion/accordion.js, blocks/document-center/document-center.js, blocks/faq-accordion/faq-accordion.js, scripts/utils.js
Fix #965
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/codes/
- After: https://issue-965--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/codes/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/division_of_air_quality/monitoring/
- After: https://issue-965--clarkcountynv--aemsites.aem.live/government/departments/environment_and_sustainability/division_of_air_quality/monitoring/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_preventi …
=> Implement deep linking in all accordion types

blocks/embed/embed.css
Fix #1039 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_communications/formula_1_info/
- After: https://issue1039-video-sizing--clarkcountynv--aemsites.aem.live/government/departments/public_communications/formula_1_info/
=> Add left align with size

blocks/table/table.css, styles/styles.css
Fix #1041 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_communications/our-team
- After: https://issue1041-add-table-styles-resync--clarkcountynv--aemsites.aem.live/government/departments/public_communications/our-team
=> added table styles, colors

templates/calendar/calendar.js, templates/event/event.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=07&year=2024&offset=1&limit=30
- After: https://calendar-fix--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=07&year=2024&offset=1&limit=30
=> Optimize message passing and handling

scripts/scripts.js
Fix #588 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/
- After: https://issue-588--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/
=> Email update modal for /county_treasurer/ page

blocks/document-center/document-center.js, blocks/hotline/hotline.css, blocks/hotline/hotline.js
Fix #604 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/divisions/advanced_planning_division/completed-trail-projects
- After: https://issue604-hl--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/divisions/advanced_planning_division/completed-trail-projects
=> Issue604 Enhancement to the hotline block - adding an accordion feature

blocks/hotline/hotline.js
Fix #1076 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/directory
- After:  https://issue1076--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/directory
=> Fixing the hotline issues

blocks/hotline/hotline.css, blocks/hotline/hotline.js
Fix #1078 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/adoption_program/profiles
- After: https://issue1078--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/adoption_program/profiles
=> Hotline Improvisations

blocks/hotline/hotline.css, templates/default/default.css, templates/default/default.js
…for cards & hotline
Fix #1080 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_communications/formula_1_info/
- After: https://issue1080--clarkcountynv--aemsites.aem.live/government/departments/public_communications/formula_1_info/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/divisions/advanced_planning_division/completed-trail-projects
- After: https://issue1080--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/divisions/advanced_planning_division/completed-trail-projects
=> Enablement SMS links functionality plus another version of no-button 

blocks/table/table.css, styles/styles.css
Fix #1086 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/business-license-fees
- After: https://issue1086-add-table-header-color--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/business-license-fees
=> add table color

helix-query.yaml
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1119
- After: https://news-query--clarkcountynv--aemsites.aem.page/news/news-detail-t28-r1119
=> Fix indexing yaml to show news list banner

templates/calendar/calendar.js
Fix #1093 
Test URLs:
- After: https://issue1093--clarkcountynv--aemsites.aem.live/calendar
=> Enabling the calendar based on the new ID's 

blocks/table/table.css, styles/styles.css
Fix #1094 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/resources-helpful-links
- After: https://issue1094-add-table-header-color--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/resources-helpful-links
=> add another table color

tools/importer/import-events-index.js, tools/importer/import-events.js
Test URLs:
- After: https://calendar-importer-fix--clarkcountynv--aemsites.aem.live/calendar
=> Enhance event importer for multiple division names + allDay

helix-query.yaml
=> Added exclusion for all calendar division index pages

helix-query.yaml, scripts/utils.js, templates/calendar/calendar.js, templates/event/event.js
Fix #1099
URL will work only when indexes are updated
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=01&year=2025&id=61-2219
- After: https://issue-1099--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=01&year=2025&id=61-2219
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=12&year=2024&id=55-2619
- After: https://issue-1099--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=12&year=2024&id=55-2619
=> Support for allDay events in Calendar

templates/calendar/calendar.js
Fix #1105 
Test URLs:
- After: https://issue1105--clarkcountynv--aemsites.aem.live/calendar
=> Enablement of close button for certain events which were not coming

blocks/newslist/newslist.css, blocks/newslist/newslist.js, icons/search-arrow.svg, scripts/ffetch.js, scripts/utils.js, templates/default/default.css
Fix #419 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/newslist
- After: https://issue419-newslist--clarkcountynv--aemsites.aem.live/newslist
=> News List Implementation

blocks/newslist/newslist.js, templates/calendar/calendar.js
Fix #1114 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar/county-commission-district-a/?view=month&day=01&month=04&year=2025
- After: https://issue1114--clarkcountynv--aemsites.aem.live/calendar/county-commission-district-a/?view=month&day=01&month=04&year=2025
=> Fixing the individual calendar bug

templates/calendar/calendar.js
Fix #1107
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=day&day=25&month=02&year=2025
- After: https://issue-1107--clarkcountynv--aemsites.aem.live/calendar?view=day&day=25&month=02&year=2025
=> Calendar - Support for - & + day of week

blocks/document-center/document-center.css, blocks/document-center/document-center.js, templates/default/default.css, tools/importer/import-leftnav.js
Fix #877 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/drafts/akasjain/demographics
- After: https://doc-centre-ml-block--clarkcountynv--aemsites.aem.live/drafts/akasjain/demographics
- Before: https://main--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/district_e/newsletters
- After: https://doc-centre-ml-block--clarkcountynv--aemsites.aem.live/government/board_of_county_commissioners/district_e/newsletters
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/forms
- After: https://doc-centre-ml-block--clarkcountynv--aemsites.aem.live/ …
=> Implement support for 2 level document center accordion

blocks/newslist-hp/newslist-hp.css, blocks/newslist-hp/newslist-hp.js
Fix #1119 
Test URLs:
- After: https://issue1119--clarkcountynv--aemsites.aem.live/
=> Newlist implementation for the Home Page

blocks/cards/cards.css, tools/importer/import-business-detail.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/winchester_dondero_cultural_center/life-in-death-festival
- After: https://importer-business-detail--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/cultural_division/winchester_dondero_cultural_center/life-in-death-festival
=> Importer business detail

templates/calendar/calendar.js
Fix #1118
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=12&year=2025
- After: https://issue1118-daily--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=12&year=2025
Testing the daily calendar event - - - > https://main--clarkcountynv--aemsites.aem.live/calendar/parks-and-recreation/testing-daily-recurring
=> Adding the Daily Freq logic making sure that the excluded dates also work

blocks/table/table.css, blocks/table/table.js
Fix # UAT second round: table formatting #982
Test URLs:
- Before: https://982-uat-second-round-table-formatting--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/proposed-amendments-to-clark-county
- After: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/proposed-amendments-to-clark-county
=> blue-header-bordered commit1

blocks/video/video.js
Fix #1139 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/copper-wire-theft
- After: https://issue1139--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/copper-wire-theft
=> Fixing the bug for table video

blocks/table/table.css
Fix #1138 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/kiosk-pages
- After: https://issue1138-add-table-styles--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/kiosk-pages
=> add style for image right with size

blocks/banner-carousel/banner-carousel.css
Fix #1148 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/press
- After: https://issue1148--clarkcountynv--aemsites.aem.live/government/elected_officials/county_clerk/press
=> Fixing the height and gradient of the carousal banner hero image links

blocks/table/table.css
Fix #1156 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/forms
- After: https://issue1156-add-table-col1-sizing--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/forms
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/liquor-and-gaming-miscellaneous-forms
- After: https://issue1156-add-table-col1-sizing--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/liquor_and_gaming/liquor-and-gaming-misc …
=> add 30 percent column1 size

component-models.json
Fix #1159 
Test URLs:
- After: https://issue1159--clarkcountynv--aemsites.aem.live/
=> Adding another styling for RPTT Calculator

blocks/form/rptt-calculator.css
Fix #1158 
Test URLs:
- Before: https://main--clarkcountynv-forms--aemsites.aem.live/content/clarkcountynv-forms/rptt-calculator
- After: https://issue1158--clarkcountynv-forms--aemsites.aem.live/content/clarkcountynv-forms/rptt-calculator
=> Enablement of calculator CSS - AEM CS 

blocks/document-center/document-center.css, blocks/document-center/document-center.js, tools/importer/import-leftnav.js
Fix #877 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/divisions/franchise_services/franchisees-and-licensees
- After: https://doc-center-fix--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/divisions/franchise_services/franchisees-and-licensees
=> Document center to support sections with both single and two level documents

blocks/table/table.css
Fix #1166 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/land-documents
- After: https://issue1166-add-table-text-style--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/land-documents
=> add h2 for align top text

styles/styles.css, templates/default/default.css, tools/importer/import-leftnav.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/contactus
- After: https://url-fix--clarkcountynv--aemsites.aem.page/contactus
=> line-break support for all templates

blocks/form/contact-us.css, blocks/form/rptt-calculator.css, templates/default/default.css, templates/default/default.js
Fix #1174 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/rptt-calculator
- After: https://issue1172--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/rptt-calculator
=> Enablement of RPTT calculator form onto EDS Docx

blocks/form/contact-us.css, blocks/form/form.css, blocks/form/models/form-common/_help-container.json, blocks/form/util.js, component-models.json
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/form-tooltip-test
- After: https://tooltip-aj--clarkcountynv--aemsites.aem.page/drafts/akasjain/form-tooltip-test
=> Tooltip functionality 

component-models.json
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/akasjain/form-tooltip-test
- After: https://enable-tooltip--clarkcountynv--aemsites.aem.page/drafts/akasjain/form-tooltip-test
=> Enable tooltip for multiline input

blocks/form/contact-us.css, component-models.json
Fix #1185 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/residents/family_services/parenting-classes
- After: https://issue1185--clarkcountynv--aemsites.aem.page/residents/family_services/parenting-classes
=> Issue1185 - Distinguish between contact-us form CSS and contact us site css

blocks/table/table.css, styles/styles.css
Fix #855-UAT
Test URLs:
- Before: https://855-uat--clarkcountynv--aemsites.aem.page/business/doing_business_with_clark_county/divisions/general_business/general-license-guide
- After: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/general_business/general-license-guide
=> 855-UAT commit1

blocks/form/contact-us.css
Fix #1190 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/franchise-online-complaint-form
- After: https://issue1190--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/franchise_services/franchise-online-complaint-form
=> Adding more to contact us form css

blocks/form/functions.js
Test URLs:
- After: https://replace-string--clarkcountynv--aemsites.aem.live/
=> Replace string custom function

blocks/form/functions.js
Test URLs:
- Before: https://main--clarkcountynv-forms--aemsites.aem.live/
- After: https://woraround-ruleeditor--clarkcountynv-forms--aemsites.aem.live/
=> Fixing custom function

blocks/header/header.css, blocks/header/header.js, blocks/search-results/search-results.css, blocks/search-results/search-results.js, scripts/delayed.js, templates/search/search.css, templates/search/search.js, widgets/googlesearch/googlesearch.js
Fix #1196 
Test URLs:
- After: https://issue1196--clarkcountynv--aemsites.aem.live/
=> Search Functionality enablement 

blocks/form/_form.json, blocks/form/components/checkbox-with-others/_checkbox-with-others.json, blocks/form/components/checkbox-with-others/checkbox-with-others.js, blocks/form/form.js, blocks/form/mappings.js, blocks/form/rules/index.js, blocks/form/util.js, component-definition.json, component-filters.json, component-models.json, models/_button.json, models/_component-definition.json, models/_component-filters.json, models/_component-models.json, models/_image.json, models/_section.json, models/_text.json, models/_title.json, package-lock.json, package.json, scripts/form-editor-support.js
Test URLs:
- After: https://custom-checkbox--clarkcountynv--aemsites.aem.live/
=> Custom checkbox with others

blocks/form/form.js
Test URLs:
- After: https://fix-embed--clarkcountynv--aemsites.aem.live/
=> fix: form embed

helix-query.yaml
Fix #1214 
Test URLs:
- After: https://issue1214--clarkcountynv--aemsites.aem.live/
=> Adding year to the helix query

blocks/form/functions.js
Test URLs:
- After: https://dropdown--clarkcountynv--aemsites.aem.live/
=> add custom function for concern

blocks/table/table.css
Fix [#495](https://github.com/aemsites/clarkcountynv/issues/495)
Test URLs:
- Before: https://495-uat-image-inconsistencies--clarkcountynv--aemsites.aem.page/government/departments/comprehensive_planning_department/boards_and_commissions/planning-commissioners
- After: https://main--clarkcountynv--aemsites.aem.live/government/departments/comprehensive_planning_department/boards_and_commissions/planning-commissioners
=> 495-uat-image-inconsistencies commit1

blocks/banner-carousel/banner-carousel.css, blocks/banner-carousel/banner-carousel.js, scripts/scripts.js
Fix #631
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/elected_officials/county_clerk/press
- After: https://issue-631--clarkcountynv--aemsites.aem.page/government/elected_officials/county_clerk/press
=> Implement breadcrumbs in banner-carousel + media fixes

blocks/footer/footer.css, blocks/footer/footer.js, scripts/utils.js, tools/importer/import-announcement.js
Fix #1202
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_communications/newsletters/subscribe-unsubscribe
- After: https://issue-1202--clarkcountynv--aemsites.aem.live/government/departments/public_communications/newsletters/subscribe-unsubscribe
=> Footer fixes

templates/calendar/calendar.js
Fix #1092 
Test URLs:
- After: https://issue-1092--clarkcountynv--aemsites.aem.live/calendar
=> Issue 1092

blocks/cards/cards.css, blocks/embed/embed.css, blocks/embed/embed.js, blocks/table/table.css, styles/styles.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/regulated_business/regulated-license-guide
- After: https://style-fixes--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/regulated_business/regulated-license-guide
- Before: https://main--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/drivers-independent-contractors
- After: https://style-fixes--clarkcountynv--aemsites.aem.live/business/doing_business_with_clark_county/divisions/drivers-independent-contractors
- Before: …
=> Style fixes

blocks/form/contact-us.css, blocks/form/form.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/about-us
- After: https://small-form-style--clarkcountynv--aemsites.aem.live/government/departments/parks___recreation/about-us
=> Style for form with small width

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #1207 
Test URLs:
- After: https://issue-1092--clarkcountynv--aemsites.aem.live/calendar
=> Calendar pending issues 

blocks/header/header.css, blocks/search-results/search-results.js, scripts/delayed.js
Fix #1227 
Test URLs:
- After: https://issue-1227--clarkcountynv--aemsites.aem.live/
=> Search Implementation bugs

blocks/embed/embed.js
Fix #587 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/
- After: https://embed-dynamic-size--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/
=> feat: Allow dynamic sizing of iframe inside embed block

blocks/cards/_cards.json, blocks/columns/_columns.json, blocks/embed-adaptive-form/_embed-adaptive-form.json, blocks/embed-adaptive-form/embed-adaptive-form.css, blocks/embed-adaptive-form/embed-adaptive-form.js, blocks/form/models/form-common/_help-container.json, blocks/fragment/_fragment.json, blocks/hero/_hero.json, component-definition.json, component-filters.json, component-models.json, models/_section.json
Test URLs:
- Before: https://main--clarkcountynv-forms--aemsites.aem.live
- After: https://model-changes--clarkcountynv-forms--aemsites.aem.live
=> Model changes in underscore files for persistence

blocks/form/rptt-calculator.css
Fix #1203 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/rptt-calculator
- After: https://issue-1203--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/rptt-calculator
=> RPTT Calculator

blocks/table/table.css
Fix #1245 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_communications/social-media
- After: https://issue1245--clarkcountynv--aemsites.aem.live/government/departments/public_communications/social-media
=> Fixing the spacing for the social media page

blocks/header/header.css, blocks/header/header.js, scripts/scripts.js, scripts/utils.js, styles/styles.css
Fix #158 
Test URLs:
- After: https://issue-158-header--clarkcountynv--aemsites.aem.live/
=> Changing the media query from 900 to 991 for header

blocks/carousel/carousel.css, blocks/header/header.js, blocks/hero/hero.css, blocks/newslist-hp/newslist-hp.js, blocks/search-results/search-results.js, blocks/tabs/tabs.css, blocks/tabs/tabs.js, styles/styles.css, templates/default/default.css
Fix #1206 
Test URLs:
- After: https://issue-1206-hp--clarkcountynv--aemsites.aem.live/
=> Fixing all bugs on the Home Page

scripts/delayed.js
Fix #426 #301 
Test URLs:
- After: https://issue-426-analytics--clarkcountynv--aemsites.aem.live/
- Before: https://main--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/foster_care/
- After: https://issue-426-analytics--clarkcountynv--aemsites.aem.live/residents/family_services/divisions/foster_care/
=> Issue 426 & 301 Configuring Analytics

blocks/faq-accordion/faq-accordion.css
Fix #1066 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/development/development-review#development-process-drainage-study
- After: https://issue-1066--clarkcountynv--aemsites.aem.live/government/departments/public_works_department/development/development-review#development-process-drainage-study
=> Adjusting more height

blocks/header/header.css
Fix #1251 
Test URLs:
- After: https://issue-1251--clarkcountynv--aemsites.aem.live/
=> Fixing text allign

blocks/carousel/carousel.css, blocks/columns/columns.js, blocks/featured-events/featured-events.js, blocks/footer/footer.js, blocks/header/header.js, blocks/newslist-hp/newslist-hp.js, scripts/delayed.js
Fix #1256 
Test URLs:
- After: https://issue-1128-accessibility--clarkcountynv--aemsites.aem.live/
=> Accessibility Improvization

templates/calendar/calendar.js
Fix #1254 
Test URLs:
- After: https://issue-1254--clarkcountynv--aemsites.aem.live/calendar
=> Updating to 5 weeks

helix-query.yaml
Fix #1261 
Test URLs:
- After: https://issue-1261--clarkcountynv--aemsites.aem.live/
=> Checking for TZ

blocks/newslist/newslist.js, helix-query.yaml
Fix #1259 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/newslist
- After: https://issue-1259--clarkcountynv--aemsites.aem.live/newslist
=> Issue 1259

blocks/header/header.js, templates/calendar/calendar.js
Fix #1260 
Test URLs:
- After: https://issue-1260--clarkcountynv--aemsites.aem.live/
=> Improving SEO

blocks/featured-events/featured-events.css
Fix #1253 
Test URLs:
- After: https://issue-1253--clarkcountynv--aemsites.aem.live/
=> Fixing the aspect ratio of featured images

helix-query.yaml
Fix #1272 
Test URLs:
- After: https://issue-1272--clarkcountynv--aemsites.aem.live/calendar
=> Enabling calendar departments landing index pages to be indexed

blocks/header/header.css
Fix #820 
Test URLs:
- After: https://issue-820--clarkcountynv--aemsites.aem.live/
=> Issue 820 

helix-sitemap.yaml
Fix #1277 
Test URLs:
- After: https://issue-1277-sitemap--clarkcountynv--aemsites.aem.live/
=> Configuriung the sitemap.xml

blocks/form/contact-us.css, blocks/newslist/newslist.js, helix-query.yaml
Fix #1137
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/newslist?category=all-news
- After: https://issue-1137--clarkcountynv--aemsites.aem.live/newslist?category=all-news
- Before: https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/request-a-speaker
- After: https://issue-1137--clarkcountynv--aemsites.aem.live/government/elected_officials/county_recorder/request-a-speaker
=> News List - Date format- Comma missing

scripts/delayed.js
Fix #1283 
Test URLs:
- After: https://issue-1283--clarkcountynv--aemsites.aem.live/
=>  Analytics

blocks/header/header.css
Fix #1289 
Test URLs:
- After: https://issue-1289--clarkcountynv--aemsites.aem.live/
=> Removing the margin - right

robots.txt
Fix #1286 
Test URLs:
- After: https://issue-1286--clarkcountynv--aemsites.aem.live/
=> Enabling the Robots - Go Live

scripts/ffetch.js, templates/calendar/calendar.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=05&year=2025&id=24-2019
- After: https://calendar-read-more--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=05&year=2025&id=24-2019
=> Modify ReadMore URL to use current origin

blocks/featured-events/featured-events.css, blocks/featured-events/featured-events.js, blocks/newslist-hp/newslist-hp.js
Fix #1301 
Test URLs:
- After: https://issue1301-seo--clarkcountynv--aemsites.aem.live/
=> Updating SEO factors

blocks/featured-events/featured-events.css, blocks/featured-events/featured-events.js
Fix #1302 
Test URLs:
- After: https://issue-1303--clarkcountynv--aemsites.aem.live/
=> Issue 1303 - SEO - 100

blocks/featured-events/featured-events.js
Fix #1307 
Test URLs:
- After: https://issue1307--clarkcountynv--aemsites.aem.live/
=> Removong links from Calendar events description in the featured section

blocks/form/form.css, blocks/form/form.js, blocks/form/rules/index.js, blocks/form/submit.js
Fix #1218 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/contactus
- After: https://issue1218-spinner--clarkcountynv--aemsites.aem.live/contactus
=> Issue1218 spinner

tools/importer/import-parent.js
Fix #1311 
Test URLs:
- After: https://issue1311--clarkcountynv--aemsites.aem.live/
=> Adding a parent importer for the new path revize/clarkcounty

templates/calendar/calendar.css
Fix #1298 
Test URLs:
- After: https://issue1298-calendar--clarkcountynv--aemsites.aem.live/calendar?
=> Fixing the calendar mobile view

templates/default-d1/default-d1.css, templates/default-d1/default-d1.js
Fix #1322 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/drafts/meet/department1/ballot-organization-and-rules
- After: https://issue1322--clarkcountynv--aemsites.aem.page/drafts/meet/department1/ballot-organization-and-rules
=> Enablement of Fragments

blocks/cards/cards.css, blocks/cards/cards.js, blocks/header/header.js
Fix #1128 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/assessor/property_search/
- After: https://issue-1128--clarkcountynv--aemsites.aem.live/government/assessor/property_search/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/
- After: https://issue-1128--clarkcountynv--aemsites.aem.live/government/departments/
-
=> Issue 1128 - Accessibility fix

blocks/header/header.js
Fix #1314 
Test URLs:
- After: https://main--clarkcountynv--aemsites.aem.live/
=> Fixing the mobile behaviour

blocks/banner-carousel/banner-carousel.css, blocks/header/header.js
Fix #1305 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/fire/
- After: https://issue-1305--clarkcountynv--aemsites.aem.live/government/departments/fire/
- Before: https://main--clarkcountynv--aemsites.aem.live/government/departments/fire/executive-team-1
- After: https://issue-1305--clarkcountynv--aemsites.aem.live/government/departments/fire/executive-team-1
=> Sub menu does not open on mobile or in mobile inspect mode with carousal

templates/event/event.js
Fix #1299 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar/county-commissioners/bcc-meeting-2024-04-02t09-00-00
- After: https://issue-1299--clarkcountynv--aemsites.aem.live/calendar/county-commissioners/bcc-meeting-2024-04-02t09-00-00
=> Fixing the event template

scripts/utils.js, templates/event/event.js
Fix #1299 
Test URLs:
- After: https://issue1299v1--clarkcountynv--aemsites.aem.live/
=> Fixing the events links

scripts/utils.js
Fix #1299 
Test URLs:
- After: https://issue1299v2--clarkcountynv--aemsites.aem.live/
=> Fixing the links

blocks/table/table.css, scripts/utils.js, templates/event/event.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/calendar?view=month&day=01&month=05&year=2025&id=28-5119
- After: https://misc-fixes--clarkcountynv--aemsites.aem.page/calendar?view=month&day=01&month=05&year=2025&id=28-5119
=> Open event detail links in a new tab

blocks/header/header.css
Fix #1340 
Test URLs:
- After: https://issue-1296--clarkcountynv--aemsites.aem.live/
=> Issue 1340

templates/calendar/calendar.css, templates/calendar/calendar.js
Fix #1082 
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=05&year=2025&id=57-1719
- After: https://issue-1082--clarkcountynv--aemsites.aem.live/calendar?view=month&day=01&month=05&year=2025&id=57-1719
=> Calendar events text color bug

blocks/document-center/document-center.js
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/rural-connections-newsletters
- After: https://empty-category-fix--clarkcountynv--aemsites.aem.page/government/board_of_county_commissioners/rural-connections-newsletters
=> fix: Fix for empty category in document center

styles/styles.css
Fix #[1352](https://github.com/aemsites/clarkcountynv/issues/1352)
Test URLs:
- After: https://feature-1352-global-pallete-change--clarkcountynv--aemsites.aem.live/
Updated global palette color change to use new color set from designs.
=> Feature: Issue #1352  - Global - Palette Color Change

styles/styles.css
Fix #[1350](https://github.com/aemsites/clarkcountynv/issues/1350)
Test URLs:
- After: https://feature-1350-a11y-title-style-updates--clarkcountynv--aemsites.aem.live/
Global Title Sizing Updates - Desktop
=> Feature: Issue #1350 - Global - Title Style Updates

blocks/accordion/accordion.css, blocks/faq-accordion/faq-accordion.css, blocks/faq-accordion/faq-accordion.js, icons/chevron-down.svg, icons/chevron-up.svg, icons/search-close.svg
Fix #[<1355>](https://github.com/aemsites/clarkcountynv/issues/1355)
Test URLs:
- After: https://feature-1355-accordion-faq-updates--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1355 - Accordion Updates

blocks/table/table.css, blocks/table/table.js
Fix #[1362](https://github.com/aemsites/clarkcountynv/issues/1362)
Test URLs:
- After: https://feature-1362-table-updates-final--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1362 - Agenda No-Header Table Updates

blocks/horizontal-rule/horizontal-rule.css, blocks/horizontal-rule/horizontal-rule.js, styles/styles.css
Fix #[1365](https://github.com/aemsites/clarkcountynv/issues/1365)
Test URLs:
- After: https://feature-1365-horizontal-rule--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1365 - Horizontal Rule Component

blocks/text/text.css, styles/styles.css
Fix #[1371](https://github.com/aemsites/clarkcountynv/issues/1371)
Test URLs:
- After: https://feature-1371-text-eyebrow--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1371 - Text Eyebrow Style

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #[1373](https://github.com/aemsites/clarkcountynv/issues/1373)
Test URLs:
- After: https://feature-1373-column-contact-card--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1373 - Column Contact Card (Map Embed)

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #[1372](https://github.com/aemsites/clarkcountynv/issues/1372)
Test URLs:
- After: https://feature-1372-text-columns-img--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1372 - Columns - 2 Column Text/Image

blocks/columns/columns.css
Fix #[1388](https://github.com/aemsites/clarkcountynv/issues/1388)
Test URLs:
- After: https://feature-1388-two-column-text--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1388 - 2 Column Text Layout

scripts/delayed.js, widgets/googlesearch/googlesearch.js
=> Added loadPodcastStreamingAudio

scripts/aem-assets-plugin-support.js
=> fixed link error

tools/assets-selector/config.json
=> removed assetmapping

scripts/aem.js, scripts/scripts.js
=> reverted code

blocks/text/text.css
Fix #[1371](https://github.com/aemsites/clarkcountynv/issues/1371)
Test URLs:
- After: https://issue-1371-text-eyebrow-issue--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1371 - Text Eyebrow Sizing

styles/styles.css
Fix #[<gh-issue-id>](https://github.com/aemsites/clarkcountynv/issues/1350)
Test URLs:
- After: https://issue-1350-title-style-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1350 - Title Style - Sizing Issues 

blocks/hero/hero.css, blocks/hero/hero.js, scripts/scripts.js, styles/styles.css
Fix #[1369](https://github.com/aemsites/clarkcountynv/issues/1369)
Fix #[1364](https://github.com/aemsites/clarkcountynv/issues/1364)
Test URLs:
- After: https://feature-1369-homepage-hero-style--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1369 + Issue #1364 - Homepage Hero Banner + Styles

blocks/columns/columns.css
Fix #[1399](https://github.com/aemsites/clarkcountynv/issues/1399)
Test URLs:
- After: https://feature-1399-featured-story--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1399 - Featured Story - Columns Highlight

tools/assets-selector/config.json
=> Sidekick asset inte jul18

scripts/aem.js, scripts/scripts.js
=> added aasset integration code july 18

blocks/newslist-hp/newslist-hp.css, blocks/newslist-hp/newslist-hp.js
Fix #[1400](https://github.com/aemsites/clarkcountynv/issues/1400)
Test URLs:
- After: https://feature-1400-featured-news-list--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1400 - Featured News List

blocks/table/table.css
Fix #[1362](https://github.com/aemsites/clarkcountynv/issues/1362)
Test URLs:
- After: https://issue-1362-table-adjustments--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1362 - Table - Agenda No-Header Variation

blocks/top-topics/top-topics.css, blocks/top-topics/top-topics.js
Fix #[1395](https://github.com/aemsites/clarkcountynv/issues/1395)
Test URLs:
- After: https://issue-1395-top-topics-a11y--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1395 - A11y fixes for Top Topics

blocks/video/video.css
Fix #[1356](https://github.com/aemsites/clarkcountynv/issues/1356)
Test URLs:
- After: https://issue-1356-video-styling-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1356 - Video - Styling Issues

templates/default/default.js, templates/event/event.js, templates/full/full.js
=> Links to images fix

blocks/accordion/accordion.css
Fix #[1355](https://github.com/aemsites/clarkcountynv/issues/1355)
Test URLs:
- After: https://issue-1355-accordion-fixes--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1355 - Accordion - Updated styles.

blocks/fragment/fragment.js, blocks/header/header.js, blocks/modal/modal.css, blocks/modal/modal.js, scripts/delayed.js, templates/calendar/calendar.css, templates/calendar/calendar.js, templates/event/event.css, templates/event/event.js
Fix #[1403](https://github.com/aemsites/clarkcountynv/issues/1403)
Test URLs:
- After: https://feature-1403-calendar-landing-page--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1403 - Calendar Landing Page

blocks/document-center/document-center.css
Fix #[1357](https://github.com/aemsites/clarkcountynv/issues/1357)
Test URLs:
- After: https://issue-1357-document-center-a11y--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1357 - Document Center - Input Color A11y

templates/calendar/calendar.css, templates/calendar/calendar.js, templates/event/event.js
Fix #[1403](https://github.com/aemsites/clarkcountynv/issues/1403)
Test URLs:
- After: https://issue-1403-calendar-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1403 - Calendar Accessibility

blocks/hotline/hotline.css, blocks/hotline/hotline.js
Fix #[1466](https://github.com/aemsites/clarkcountynv/issues/1466)
Test URLs:
- After: https://issue-1466-hotline-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1466 - Hotline Issues

blocks/footer/footer.css, blocks/header/header.css, styles/styles.css
Fix #[1370](https://github.com/aemsites/clarkcountynv/issues/1370)
Test URLs:
- After: https://issue-1370-footer-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1370 - Footer Issues

templates/calendar/calendar.css
Test URLs:
- Before: https://main--clarkcountynv--aemsites.aem.page/calendar?view=list&day=01&month=08&year=2025
- After: (https://1481-calendar--clarkcountynv--aemsites.aem.page/calendar?view=list&day=01&month=08&year=2025)
=> calendar title

blocks/document-center/document-center.css
=> 1471 document

blocks/alert-popup/alert-popup.css, blocks/alert-popup/alert-popup.js, blocks/footer/footer.css, scripts/scripts.js, styles/styles.css
Fix #[1397](https://github.com/aemsites/clarkcountynv/issues/1397)
Test URLs:
- After: https://issue-1397-alert-banner-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1397 - Alert Banner - Focus States

helix-query.yaml
=> removed fragments

blocks/footer/footer.css
Fix #[1482](https://github.com/aemsites/clarkcountynv/issues/1482)
Test URLs:
- After: https://feature-1482-footer-subscribe--clarkcountynv--aemsites.aem.live/
=> Feature: Issue #1482 - Footer Subscribe

helix-query.yaml
=> Query index

blocks/footer/footer.css, blocks/form/form.css, blocks/header/header.css, blocks/hotline/hotline.css, styles/styles.css, templates/default/default.css
Fix #[1557](https://github.com/aemsites/clarkcountynv/issues/1557)
Fix #[1542](https://github.com/aemsites/clarkcountynv/issues/1542)
Fix #[1541](https://github.com/aemsites/clarkcountynv/issues/1541)
Fix #[1530](https://github.com/aemsites/clarkcountynv/issues/1530)
Fix #[1520](https://github.com/aemsites/clarkcountynv/issues/1520)
Test URLs:
- After: https://feature-release-fixes--clarkcountynv--aemsites.aem.live/
=> Bug: Release Fixes

blocks/accordion/accordion.css, blocks/document-center/document-center.css, blocks/faq-accordion/faq-accordion.css, blocks/hotline/hotline.css, icons/chevron-down-grey.svg, icons/chevron-up-orange.svg, templates/default/default.css
Fix #[1565](https://github.com/aemsites/clarkcountynv/issues/1565)
Fix #[1566](https://github.com/aemsites/clarkcountynv/issues/1566)
Test URLs:
- After: https://issue-1565-caret-icons-direction--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1565 + #1566 - Caret Icons + No-Button Link Styles

blocks/cards/cards.css
Fix #[1564](https://github.com/aemsites/clarkcountynv/issues/1564)
Test URLs:
- After: https://issue-1564-card-logo-issues--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1564 - Card Logo Issues

blocks/header/header.css, styles/styles.css
Fix #[1586](https://github.com/aemsites/clarkcountynv/issues/1586)
Test URLs:
- After: https://issue-1586-header-logo-and-size--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1586 - Header Logo + Size

blocks/form/form.css
Fix #[1585](https://github.com/aemsites/clarkcountynv/issues/1585)
Test URLs:
- After: https://issue-1585-form-submit-button--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1585 - Form Submit Button - New Line

blocks/header/header.css
Fix #[1586](https://github.com/aemsites/clarkcountynv/issues/1586)
Test URLs:
- After: https://issue-1586-mobile-logo-size--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1586 - Header Mobile Logo Size

blocks/columns/columns.css, blocks/columns/columns.js
Fix #[1583](https://github.com/aemsites/clarkcountynv/issues/1583)
Test URLs:
- After: https://issue-1583-contact-card-img--clarkcountynv--aemsites.aem.live/
=> Bug: Issue #1583 - Columns Contact Card - Image Variation
